# Generated by Django 5.2.7 on 2026-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStoreApp', '0008_address_last_used_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
    ]
