# Generated by Django 5.2.7 on 2026-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStoreApp', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(),
        ),
    ]
